import argparse
import csv
import math
from collections import defaultdict


WHEEL_NAMES = ("fl", "fr", "rl", "rr")


def to_float(value):
    if value is None or value == "":
        return None
    try:
        x = float(value)
    except ValueError:
        return None
    if not math.isfinite(x):
        return None
    return x


def sign_of(value, eps=1e-4):
    if value is None or abs(value) < eps:
        return 0
    return 1 if value > 0.0 else -1


def mean(values):
    vals = [v for v in values if v is not None]
    if not vals:
        return None
    return sum(vals) / len(vals)


def pct(count, total):
    if total <= 0:
        return None
    return 100.0 * count / total


def fmt(value, digits=3):
    if value is None:
        return "-"
    return f"{value:.{digits}f}"


def analyze(csv_path, phase):
    groups = defaultdict(list)
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("phase") != phase:
                continue
            test = row.get("test", "")
            if not test:
                continue
            groups[test].append(row)

    summaries = []
    for test, rows in groups.items():
        for wheel in WHEEL_NAMES:
            cmd_key = f"dbg_wheel_cmd_{wheel}"
            enc_key = f"dbg_enc_vel_corr_{wheel}"
            motor_key = f"dbg_motor_u_{wheel}"

            cmd_vals = [to_float(r.get(cmd_key)) for r in rows]
            enc_vals = [to_float(r.get(enc_key)) for r in rows]
            motor_vals = [to_float(r.get(motor_key)) for r in rows]

            samples = [
                (cmd, enc, motor)
                for cmd, enc, motor in zip(cmd_vals, enc_vals, motor_vals)
                if cmd is not None and enc is not None and motor is not None
            ]
            active = [(cmd, enc, motor) for cmd, enc, motor in samples if abs(cmd) >= 0.01]
            if not active:
                continue

            abs_errors = [abs(cmd - enc) for cmd, enc, _ in active]
            signed_errors = [cmd - enc for cmd, enc, _ in active]
            abs_cmd = [abs(cmd) for cmd, _, _ in active]
            abs_enc = [abs(enc) for _, enc, _ in active]

            zero_motor = sum(1 for _, _, motor in active if abs(motor) < 0.03)
            sign_bad = sum(1 for cmd, enc, _ in active if sign_of(cmd) * sign_of(enc) < 0)

            motor_flips = 0
            last_sign = 0
            for _, _, motor in active:
                s = sign_of(motor, eps=0.03)
                if s != 0 and last_sign != 0 and s != last_sign:
                    motor_flips += 1
                if s != 0:
                    last_sign = s

            ratio = None
            mean_abs_cmd = mean(abs_cmd)
            mean_abs_enc = mean(abs_enc)
            if mean_abs_cmd and mean_abs_cmd > 1e-6 and mean_abs_enc is not None:
                ratio = mean_abs_enc / mean_abs_cmd

            summaries.append({
                "test": test,
                "wheel": wheel,
                "samples": len(active),
                "cmd_abs_mean": mean_abs_cmd,
                "enc_abs_mean": mean_abs_enc,
                "ratio": ratio,
                "error_abs_mean": mean(abs_errors),
                "error_signed_mean": mean(signed_errors),
                "zero_motor_pct": pct(zero_motor, len(active)),
                "sign_bad_pct": pct(sign_bad, len(active)),
                "motor_flips": motor_flips,
            })

    return summaries


def print_summary(summaries):
    if not summaries:
        print("No command-phase debug samples found. Check /esp32/debug columns in the CSV.")
        return

    header = (
        "test",
        "wheel",
        "n",
        "|cmd|",
        "|enc|",
        "enc/cmd",
        "mean|err|",
        "mean err",
        "motor0%",
        "signbad%",
        "uflips",
    )
    widths = (14, 5, 5, 8, 8, 8, 9, 9, 8, 9, 6)
    print(" ".join(h.ljust(w) for h, w in zip(header, widths)))
    print(" ".join("-" * w for w in widths))

    for item in summaries:
        values = (
            item["test"],
            item["wheel"],
            str(item["samples"]),
            fmt(item["cmd_abs_mean"]),
            fmt(item["enc_abs_mean"]),
            fmt(item["ratio"]),
            fmt(item["error_abs_mean"]),
            fmt(item["error_signed_mean"]),
            fmt(item["zero_motor_pct"], 1),
            fmt(item["sign_bad_pct"], 1),
            str(item["motor_flips"]),
        )
        print(" ".join(v.ljust(w) for v, w in zip(values, widths)))


def parse_args():
    parser = argparse.ArgumentParser(description="Analyze wheel_response_test CSV logs.")
    parser.add_argument("csv_path", help="CSV generated by wheel_response_test.")
    parser.add_argument("--phase", default="command", help="CSV phase to analyze.")
    return parser.parse_args()


def main():
    args = parse_args()
    summaries = analyze(args.csv_path, args.phase)
    print_summary(summaries)


if __name__ == "__main__":
    main()
