/**:
  ros__parameters:
    general:
      grab_resolution: 'VGA'
      grab_frame_rate: 15
      pub_resolution: 'CUSTOM'
      pub_downscale_factor: 4.0
      grab_compute_capping_fps: 10.0
      pub_frame_rate: 5.0

    video:
      publish_rgb: false
      publish_left_right: false
      publish_raw: false
      publish_gray: false
      publish_stereo: false

    sensors:
      sensors_image_sync: false
      sensors_pub_rate: 100.0
      publish_imu: true
      publish_imu_raw: false
      publish_cam_imu_transf: false
      publish_mag: false
      publish_baro: false
      publish_temp: false

    depth:
      depth_mode: 'NONE'
      depth_stabilization: 0
      point_cloud_freq: 0.0
      publish_depth_map: false
      publish_depth_info: false
      publish_point_cloud: false
      publish_depth_confidence: false
      publish_disparity: false

    pos_tracking:
      pos_tracking_enabled: false
      publish_tf: false
      publish_map_tf: false
      publish_odom_pose: false
      publish_pose_cov: false
      publish_cam_path: false

    mapping:
      mapping_enabled: false

    object_detection:
      od_enabled: false
